<template>
  <header>
    <div class="container">
      <div class="row">
        <nav class="right-float">
            <a class="btn-pill">{{ $t("navigation.home") }}</a>
            <a class="btn-pill">{{ $t("navigation.spents") }}</a>
            <a class="btn-pill">{{ $t("navigation.about") }}</a>
            <a class="btn btn-pill btn-primary-outline">{{ $t("navigation.admin") }}</a>
        </nav>
      </div>
    </div>
  </header>
</template>
